# Generated by Django 4.2.6 on 2023-10-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_admin_admins"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admins",
        ),
    ]
