# Generated by Django 4.2.6 on 2023-10-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_admins"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=8)),
            ],
        ),
    ]
