# Generated by Django 4.2.6 on 2023-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="img",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
