# Generated by Django 4.2.6 on 2023-10-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_products_img_alter_products_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productsbought", models.CharField(max_length=100)),
                ("totalorders", models.IntegerField()),
                (
                    "uemail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                        to_field="email",
                    ),
                ),
            ],
        ),
    ]
